### ISSUE TITLE
Идея для тебя

### ISSUE THREAD

**Issue by nitro8355** [moontr3/algo_api#7]

**Comment by FargeGoty** [comment]
никак, накручивать нарушение правил алгоритмики = бан учетной записи

**Comment by justdont0** [comment]
> Выложи как сделать накрутку algoritmika в github

Во-первых никто не хочет чтобы накручивать мог каждый
А во-вторых

**Comment by moontr3** [comment]
надо было так

**Comment by moontr3** [comment]
> 

убрал команду уже

**Comment by n0n1m** [comment]
> > 
> 
> убрал команду уже

А ну ладно

**Comment by moontr3** [comment]
а то этот кисель жалуется, да и впринципе кому надо пусть сами учат рест апи ихнее
